# Generated by Django 5.0.7 on 2024-07-21 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Maxsulot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
                ('rating', models.IntegerField()),
                ('description', models.TextField()),
                ('count', models.IntegerField()),
                ('img', models.ImageField(upload_to='img')),
            ],
        ),
    ]
