# Generated by Django 5.0.7 on 2024-07-21 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopdetail', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Related',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('img', models.ImageField(upload_to='imgs/')),
                ('price', models.IntegerField()),
            ],
        ),
    ]
