# Generated by Django 5.0.7 on 2024-07-21 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shopvegetable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('rating', models.IntegerField(default=0)),
                ('newprice', models.IntegerField(default=0)),
                ('oldprice', models.IntegerField(default=0)),
                ('img', models.ImageField(upload_to='shop/')),
            ],
        ),
    ]
